# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addit_serv_header', models.CharField(max_length=100, verbose_name='header')),
                ('addit_serv_text', models.TextField(max_length=1000, verbose_name='header')),
            ],
            options={
                'verbose_name': 'Health blog',
                'verbose_name_plural': 'Health blog',
            },
        ),
        migrations.CreateModel(
            name='HealthBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_header', models.CharField(max_length=100, verbose_name='header')),
                ('blog_text', models.TextField(max_length=1000, verbose_name='header')),
            ],
            options={
                'verbose_name': 'Health blog',
                'verbose_name_plural': 'Health blog',
            },
        ),
        migrations.CreateModel(
            name='HealthCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_name', models.CharField(max_length=100, verbose_name='health name')),
                ('health_description', models.TextField(max_length=1000, verbose_name='health description')),
            ],
            options={
                'verbose_name': 'health_name',
                'verbose_name_plural': 'health_name',
            },
        ),
        migrations.CreateModel(
            name='HealthCenterBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_header', models.CharField(max_length=100, verbose_name='health name')),
            ],
            options={
                'verbose_name': 'health_name header',
                'verbose_name_plural': 'health_name header',
            },
        ),
    ]
