# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_header', models.CharField(max_length=100, verbose_name='hotel_name')),
                ('conf_description', models.TextField(max_length=100, verbose_name='hotel_name')),
            ],
            options={
                'verbose_name': 'ConferenceService',
                'verbose_name_plural': 'ConferenceService',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_header', models.CharField(max_length=100, verbose_name='contact head')),
                ('contact_adress', models.CharField(max_length=100, verbose_name='contact_name')),
                ('contact_phone', models.CharField(max_length=1000, verbose_name='contact_name')),
                ('contact_email', models.CharField(max_length=100, verbose_name='contact_email')),
                ('contact_map', models.CharField(max_length=100, verbose_name='contact_map')),
                ('contact_description', models.TextField(max_length=100, verbose_name='contact_description')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_name', models.CharField(max_length=100, verbose_name='hotel_name')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(upload_to='hotel_gallery')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100, verbose_name='hotel_name')),
            ],
            options={
                'verbose_name': 'main hotel name',
                'verbose_name_plural': 'main hotels name',
            },
        ),
        migrations.CreateModel(
            name='RestaurantBars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_b_header', models.CharField(max_length=100, verbose_name='hotel_name')),
                ('restaurant_name', models.CharField(max_length=100, verbose_name='hotel_name')),
                ('bar_name', models.CharField(max_length=100, verbose_name='hotel_name')),
                ('r_b_name', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main.Hotels')),
            ],
            options={
                'verbose_name': 'RestaurantBars',
                'verbose_name_plural': 'RestaurantBars',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_category', models.CharField(max_length=100, verbose_name='room_name')),
                ('room_building', models.CharField(max_length=100, verbose_name='room_building')),
                ('room_num', models.CharField(max_length=10, verbose_name='number_of_rooms')),
                ('room_price', models.CharField(max_length=10, verbose_name='room_price')),
                ('room_include', models.TextField(max_length=1000, verbose_name='room_include')),
                ('room_img', models.ImageField(blank=True, null=True, upload_to='room_img')),
                ('room_hotel_name', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main.Hotels')),
            ],
            options={
                'verbose_name': 'room name',
                'verbose_name_plural': 'room name',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100, verbose_name='stock_name')),
                ('stock_description', models.TextField(max_length=1000, verbose_name='stock_name')),
                ('stock_img', models.ImageField(upload_to='stock_image')),
                ('stock_both', models.NullBooleanField()),
                ('stock_h_name', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main.Hotels')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stock',
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='gallery_name',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main.Hotels'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='contact_name',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main.Hotels'),
        ),
        migrations.AddField(
            model_name='conferenceservice',
            name='conf_name',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main.Hotels'),
        ),
    ]
