# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('short_description', models.TextField(verbose_name='hotel_name')),
                ('description', models.TextField(verbose_name='hotel_name')),
            ],
            options={
                'verbose_name': 'Дополнительные услуги',
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='header')),
                ('adress', models.CharField(max_length=100, verbose_name='adress')),
                ('phone', models.PositiveIntegerField(verbose_name='phone')),
                ('email', models.EmailField(max_length=100, verbose_name='contact_email')),
                ('map', models.CharField(max_length=100, verbose_name='contact_map')),
                ('description', models.TextField(max_length=100, verbose_name='contact_description')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='asd')),
                ('nick', models.CharField(max_length=12, verbose_name='name')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='img name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_gallery')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='hotel_name')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='room_name')),
                ('apartament', models.CharField(max_length=100, verbose_name='room_building')),
                ('room_quantity', models.SmallIntegerField(verbose_name='number_of_rooms')),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=100000, max_length=10, null=True, verbose_name='room_price')),
                ('inclusive', models.TextField(max_length=1000, verbose_name='room_include')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hotel')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('stock_both', models.NullBooleanField()),
                ('hotels', models.ManyToManyField(blank=True, to='main.Hotel')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hotel'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='hotel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Hotel'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='hotel',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main.Hotel'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Gallery'),
        ),
    ]
